#!/bin/bash
set -eu

git subtree pull --prefix .vim/bundle/undotree https://github.com/mbbill/undotree.git master --squash
git subtree pull --prefix .vim/bundle/vim-latex https://github.com/vim-latex/vim-latex.git master --squash 
