#!/bin/bash
set -eu

git subtree pull --prefix .oh-my-zsh/custom/plugins/zsh-autosuggestions https://github.com/zsh-users/zsh-autosuggestions.git master --squash
git subtree pull --prefix .oh-my-zsh/custom/plugins/zsh-completions https://github.com/zsh-users/zsh-completions.git master --squash
git subtree pull --prefix .oh-my-zsh/custom/plugins/zsh-syntax-highlighting https://github.com/zsh-users/zsh-syntax-highlighting.git master --squash
git subtree pull --prefix .vim/bundle/undotree https://github.com/mbbill/undotree.git master --squash
git subtree pull --prefix .vim/bundle/vim-latex https://github.com/vim-latex/vim-latex.git master --squash 
